### PR TITLE
Change tmp folder to platform tools directory

### PR DESCRIPTION
**Pull request by keyuan0701**

### CODE REVIEW

**Review by jianhua-git — COMMENTED** [review]
checked

**Review by xueli-hu — COMMENTED** [review]
good

**Review by pwsses — APPROVED** [review]
LGTM

**Review by prozanne — APPROVED** [review]
Thanks! Good

**Review by chunhua-liu — APPROVED** [review]

**Comment by capscrom** [comment]
LGTM

**Pull request merged**
