### PR TITLE
Add options parameter for proxy

### PR DESCRIPTION
**Pull request by keyuan0701**

### CODE REVIEW

**Review by jianhua-git — COMMENTED** [review]
checked

**Review by fjk0401 — COMMENTED** [review]
Good for me

**Review by gkl54333 — COMMENTED** [review]
+1

**Review by xueli-hu — COMMENTED** [review]
good

**Review by pwsses — APPROVED** [review]
LGTM

**Review by prozanne — APPROVED** [review]
Thanks! Nice.

**Review by chunhua-liu — APPROVED** [review]

**Pull request merged**
