### PR TITLE
Update version 1.0.0

### PR DESCRIPTION
**Pull request by keyuan0701**

### CODE REVIEW

**Review by tianhao-srcn — COMMENTED** [review]
checked

**Review by wb0716 — COMMENTED** [review]
Checked！

**Review by xujiangang-git — COMMENTED** [review]
checked

**Review by xueli-hu — COMMENTED** [review]
good

**Review by fjk0401 — COMMENTED** [review]
Good for me

**Review by jianhua-git — COMMENTED** [review]
checked

**Review by chunhua-liu — DISMISSED** [review]

**Review by prozanne — DISMISSED** [review]
Good

**Comment by capscrom** [comment]
LGTM

**Review by chunhua-liu — APPROVED** [review]

**Pull request merged**
